spring:
  profiles:
    active: local  # Set active profile here

server:
  port: 8080
  servlet:
    context-path: /

---

spring:
  config:
    activate:
      on-profile: dev
aws:
  dynamodb:
    endpoint: https://dynamodb.us-west-2.amazonaws.com
    region: us-west-2
    accessKey: ${AWS_ACCESS_KEY_ID}
    secretKey: ${AWS_SECRET_ACCESS_KEY}

---

spring:
  config:
    activate:
      on-profile: prod
aws:
  dynamodb:
    endpoint: https://dynamodb.us-west-2.amazonaws.com
    region: us-west-2
    accessKey: ${AWS_ACCESS_KEY_ID}
    secretKey: ${AWS_SECRET_ACCESS_KEY}
